spring:
  batch:
    job:
      enabled: false

  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://dpg-clu4ak5a73kc7399gb80-a.frankfurt-postgres.render.com/springbatchpostgres}
    username: ${JDBC_DATABASE_USERNAME:springbatchpostgres_user}
    password: ${JDBC_DATABASE_PASSWORD:J7oXGliqI4QbmDyyXwT7jA8zlBhi8Tx8}
    dbcp2:
      max-wait-millis: 30000
      validation-query: select 1
      validation-query-timeout: 30
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
    show-sql: true
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd'T'HH:mm:ss
      time: HH:mm:ss
springdoc:
  pathsToMatch: /api/**



