spring:
  data:
    mongodb:
      uri: ${MONGODB_DATABASE_URL:mongodb+srv://${env.MONGO_USER}:${env.MONGO_PASSWORD}@${env.MONGO_CLUSTER}
      auto-index-creation: true
  docker:
    compose:
      file: backend/docker-compose.yml
      lifecycle-management: start-only
springdoc:
  pathsToMatch: /api/**