spring:
  data:
    mongodb:
      uri: ${MONGODB_DATABASE_URL:"mongodb+srv://lmurbezv:LuisMiguel2303@clusterbanco.1vyevyh.mongodb.net/banco_database"}
      auto-index-creation: true
  docker:
    compose:
      file: backend/docker-compose.yml
      lifecycle-management: start-only
springdoc:
  pathsToMatch: /api/**